### ISSUE TITLE
Allow autocompletion callback for whole command

### ISSUE THREAD

**Issue by Erik1000** [kangalioo/poise#100]
First of, the existing API for auto completion is incredible, thank you so much for that :heart:. While implementing a command with a parameter that can be auto-filled either with values based on the current user or filled with values based on a member supplied in an extra parameter, I thought it would be great if I could access this `member` parameter in the auto complete function. 
As far as I understand the [discord documentation](https://discord.com/developers/docs/interactions/application-commands#autocomplete), in the auto complete event, everything is sent, not just the current/focused parameter. It would be great if the framework could take advantage of that maybe with an autocomplete function for the whole command instead of functions for each parameter.

**Comment by kangalio** [comment]
How would an example command with an autocomplete function for the whole command look like? Having trouble imagining

**Comment by Erik1000** [comment]
I think the function would take three parameters: the Context, the partial input from all command parameters sent from discord (probably based on [`CommandData`](https://docs.rs/serenity/latest/serenity/model/application/interaction/application_command/struct.CommandData.html)) and a selection for the currently requested/focused parameter that should be autocompleted (e.g. an enum). 

The function would then process the data and return the data for the focused parameter. Since this function would need to return different completions based on the requested parameter, it would probably need to return an enum  with an inner value as well.

Example:
```rust
#[autocomplete = "complete_my_command"]
pub async fn my_command(ctx: Context<'_>, parameter1: i32, parameter2: String) -> Result<(), _> {
    // do something
}

enum CompleteSelection {
    Parameter1,
    Parameter2,
}

enum CompleteOutput {
     Parameter1(Vec<i32>), // basically either a Stream, Iterator. Just like the current output for a single parameter
     Parameter2(Vec<String>),
}

// the selection can be determined by the framework using the `focused` bool in the auto complete request from discord
async fn complete_my_command(ctx: Context<'_>, input: Vec<CommandData>, selection: CompleteSelection) -> CompleteOutput {
    match selection {
        // complete for the selected field optionally using the provided data.
    }
}
```

**Comment by kangalio** [comment]
This seems very complex which I was afraid of. Maybe this use case is specialized enough that a manual autocomplete implementation is acceptable?

```rust
#[autocomplete = "complete_my_command"]
pub async fn my_command(ctx: Context<'_>, parameter1: i32, parameter2: String) -> Result<(), _> {
    // do something
}

async fn complete_my_command(ctx: Context<'_>, interaction: &serenity::AutocompleteInteraction) -> Result<(), Error> {
    // Find selected field in interaction.data.options

    // Send interaction.create_autocomplete_response()
}
```

**Comment by Erik1000** [comment]
Yes, I think that would work for me. I agree, that my proposal could get quite complex and hard to maintain.

**Comment by kangalio** [comment]
I realized our two ideas are problematic since you still need to declare for each parameter if they are autocomplete (Discord needs to know this).

Directly afterwards I realized that poise's API already has all the capability you need since you can access the autocomplete interaction in the callback:

```rust
async fn foo_autocomplete(ctx: Context<'_>, partial: &str) -> Vec<String> {
    let interaction = match ctx {
        Context::Application(poise::ApplicationContext {
            interaction: poise::ApplicationCommandOrAutocompleteInteraction::Autocomplete(x),
            ..
        }) => x,
        _ => unreachable!("non-autocomplete interaction in autocomplete callback"),
    };

    // Find user param
    let user = interaction.data.options.iter().find(|o| o.name == "param_name").unwrap();
    // Extract user data
    let user = match user.resolved.unwrap() {
        serenity::CommandDataOptionValue::User(x, _) => x,
        _ => unreachable!("non-user value in user parameter"),
    }

    // Return autocomplete choices
}
```

**Comment by Erik1000** [comment]
Ah, didn't think of that, great!
