### ISSUE TITLE
How do i specify a description for a slash command?

### ISSUE THREAD

**Issue by kr1s7ian** [kangalioo/poise#101]
i have looked at the examples and the docs, but i was unable to find anything about it, i have seen how to add descriptions to arguments, but cant find anything about the slash command itself.

**Comment by c43721** [comment]
@kr1s7ian Add a doc comment to the command function, that should add the value as the description to the command.

![image](https://user-images.githubusercontent.com/55610086/185183238-71dc78c4-87f7-4edd-a483-c65cc761c309.png)
Something like this. Re-register and you should be good.

**Comment by kr1s7ian** [comment]
gotcha, thanks!
