### ISSUE TITLE
Localization on prefix commands

### ISSUE THREAD

**Issue by thunderstorm010** [kangalioo/poise#102]

**Comment by kangalio** [comment]
Is this something you need for a project?

**Comment by thunderstorm010** [comment]
Not really. Would like to see it in the long run though!

**Comment by mrnossiom** [comment]
Well, as prefix commands are dying, I don't think this would be necessary.

**Comment by kangalio** [comment]
Yeah same, I fear the invested time and complexity isn't worth it
