### ISSUE TITLE
`defer_response` causes chained methods of `CreateReply` to be ignored.

### ISSUE THREAD

**Issue by AviusX** [kangalioo/poise#12]
**Current behaviour:** When the command has `defer_response` enabled, chained methods such as `.components()`, `ephemeral(true)`, etc get ignored when using slash commands but work fine when using prefix commands.

**Expected behaviour:** Chained methods of `CreateReply` such as `.components()` and `.ephemeral()` should not be ignored and work as they do when `defer_response` is disabled.

### Example code
```rs
poise::send_reply(ctx, |message| {
    message
        .embed(|embed| {
            // ... create the embed
            embed
        })
        .components(|components| { // components are not shown with defer_response enabled
            debug!("Creating components..."); // this does get executed
            // ... create components
        })
        .ephemeral(true) // this gets ignored when defer_response is enabled
})
.await?;
```

### Demonstration
<img src="https://user-images.githubusercontent.com/55204295/135748749-b5263b12-fae9-48ec-aa6e-4a19f9cb5bc4.png" width=500/>

**Comment by kangalioo** [comment]
I can explain why ephemeral doesn't work with defer_response: Discord requires you to decide ephemerality already when you defer the response. That's why `:ephemeral()` in the command body has no effect. I think I'll solve this by removing the defer_response attribute in favor of just writing `let _ = ctx.defer().await?` or `let _ = ctx.defer_ephemeral().await?` manually.

Not sure why components don't work either, I will investigate

**Comment by kangalioo** [comment]
Figured out why components don't work: the issue was a copy-paste oversight, basically

Fixed in b7b73917352a4f3dc33d1062416266c040c3c1f3

I will wait for CI to finish before merging develop into master

**Comment by AviusX** [comment]
Ah I see. Thanks for the quick fix. I'll update when you merge to master.

**Comment by kangalioo** [comment]
Merged to master

**Comment by AviusX** [comment]
Updated. Thanks! You can keep this issue until the `ephemeral` issue is fixed as well or you can close it. Your call.

**Comment by kangalioo** [comment]
Imma go ahead and close this
