### ISSUE TITLE
Unable to send message in a different channel after command was run, ::serenity::http needed

### ISSUE THREAD

**Issue by davidon-top** [kangalioo/poise#121]
This may be just me being dumb and missing something obvious

i am trying to make a announce command that will send an embed in a channel (channel, message, title are in command arguments)
tho to send it using channel.id().send_message() requires &ctx.http, is there a way to get the http somehow differently? 
or is there a different way to send embed in a channel
[main.rs](https://github.com/kangalioo/poise/files/9894016/main.txt)

**Comment by kangalio** [comment]
Use `ctx.discord()`. See https://docs.rs/poise/latest/poise/#impl-trait-parameters
