### ISSUE TITLE
How to create long-standing component interactions?

### ISSUE THREAD

**Issue by alercah** [kangalioo/poise#125]
Is there a pattern for creating long-standing component interactions that will persist across instances of the bot?

The only example I can find of component interactions is [this one](https://github.com/kangalioo/poise/blob/cd79606c041d2d9c4f08a259b4dc53eea07da35b/examples/framework_usage/commands/general.rs#L103). Unless I'm quite mistaken, because it awaits interactions in the command handler, if the bot is subsequently restarted the buttons will stop doing anything.

**Comment by kangalio** [comment]
Like in serenity, you'd do this with the event handler: https://docs.rs/poise/latest/poise/structs/struct.FrameworkOptions.html#structfield.listener. Check for Event::InteractionCreate containing a Interaction::MessageComponent.

(You can also register an EventHandler like in serenity, but the EventHandler methods don't have the poise user data as a parameter, hence you often need poise's `FrameworkOptions::listener` instead)

**Comment by alercah** [comment]
Ah, thank you!

Do you have any plans to provide a `poise` API or should I just use what you said?

**Comment by kangalio** [comment]
What I said is the intended way to do things :) Poise is meant to be a framework plugged into serenity, not a replacement for serenity's facilities
