### ISSUE TITLE
Please provide a derive for SlashArgument on enums without Display/FromStr

### ISSUE THREAD

**Issue by alercah** [kangalioo/poise#126]
The ChoiceParameter derive implements Display and FromStr unconditionally, meaning that I can't provide implementations myself, and also when I'm dealing with other creates that *also* impl Display and FromStr automatically, there is simply no way forward.

It would be helpful to me something to derive only the SlashArgument impl, as currently I've had to copy-past parts of the impl macro to my own code.

**Comment by kangalio** [comment]
Sure. I made it implement FromStr to make use of the blanket PopArgument impl so the type can be used as a prefix parameter. Instead, I guess I can make it implement PopArgument directly and just re-implement the FromStr wrapper code.

Not sure why I implemented Display, I guess just for convenience. That can be an inherent method then, or better, a trait method
