### ISSUE TITLE
Errors from SlashArgument::extract are silently ignored?

### ISSUE THREAD

**Issue by alercah** [kangalioo/poise#127]
I implemented SlashArgument::extract but the implementation was wrong and it returned an error (I had set the option type to `Number`, not `Integer`, and then used `as_u64` which failed). But there was absolutely no feedback of this mistake. I thought my bot was hanging.

**Comment by kangalio** [comment]
The returned `SlashArgError` is converted into `FrameworkError` and handled via `FrameworkOptions::on_error`. The default handler (`poise::builtins::on_error`) emits a `log::error!()`. To see this, there needs to be a logging framework enabled, like `env_logger`.

**Comment by alercah** [comment]
Ah, thanks for the explanation! Was that covered in the docs somewhere and I missed it?

**Comment by kangalio** [comment]
I think it's not covered in the docs

**Comment by kangalio** [comment]
Added to my list of common questions/gotchas to be added to the docs
