### ISSUE TITLE
Expose cached messages with ChannelDelete event.

### ISSUE THREAD

**Issue by BuyMyMojo** [kangalioo/poise#129]
Since [serenity#2194](https://github.com/serenity-rs/serenity/pull/2194) the cached messages of a channel can be exposed in the event handler but still is missing from poise's ChannelDelete event

**Comment by kangalio** [comment]
The linked PR is based on the serenity next branch. Poise's corresponding serenity-next branch uses serenity's FullEvent type, which is up-to-date: https://serenity-rs.github.io/serenity/next/serenity/client/enum.FullEvent.html#variant.ChannelDelete

**Comment by BuyMyMojo** [comment]
oops I thought the change was pulled into normal serienty 😅

**Comment by kangalio** [comment]
Unfortunately not, since it's a breaking change 🤷
