### ISSUE TITLE
Support separate look-up for prefix commands and slash commands

### ISSUE THREAD

**Issue by sugar700** [kangalioo/poise#131]
I have a command with the same name defined as both prefix command and slash command, however poise gives up after seeing first command with a given name. I would like to handle prefix command separately due to manually parsing the command by using `#[rest]`.

Essentially, the code looks like this:

```rust
#[command(prefix_command, track_edits, hide_in_help, rename = "example")]
pub async fn example_command(ctx: Context<'_>, #[rest] text: String) -> Result<(), Error> {
    let (a, b) = parse_this_somehow(text)?;
    common_code(a, b).await
}

#[command(slash_command, rename = "example")]
pub async fn example_slash(ctx: Context<'_>, a: Option<String>, b: String) -> Result<(), Error> {
    common_code(a, b).await
}

**Comment by kangalio** [comment]
You can share a command's metadata but have separate implementations by overriding Command::slash_action.

You could do this for example by adding the following Command to the commands vector: 
```rust
poise::Command {
    slash_action: example_slash().slash_action,
    ..example_command()
}
```

**Comment by sugar700** [comment]
Thanks :).
