### ISSUE TITLE
Add builtin support for intervals

### ISSUE THREAD

**Issue by CraftSpider** [kangalioo/poise#132]
It would be nice to have builtin support for running things at intervals, such as every minute or day. I've sketched out a rough API based on my implementation, that I feel is fairly general. Would this have any room for being included in the framework / any commentary on the API?

```rs
pub enum IntervalNext {
    #[default]
    Continue,
    Skip(u64),
    Stop,
}

#[derive(Clone)]
#[non_exhaustive]
pub struct IntervalOptions<U, E> {
    pub on_missed: MissedTickBehavior,
    pub frequency: Duration,
    pub on_start: fn(&Framework<U, E>) -> BoxFuture<'_, ()>,
    pub on_end: fn(&Framework<U, E>) -> BoxFuture<'_, ()>,
    pub on_error: fn(&Framework<U, E>, E) -> BoxFuture<'_, IntervalNext>,
}

impl<U, E> Default for IntervalOptions<U, E> {
    fn default() -> Self;
}

pub struct Interval<U, E> { ... }

impl<U, E> Interval<U, E>
where
    U: Send + Sync + 'static,
    E: Send + Sync + 'static,
{
    pub fn builder() -> IntervalBuilder<U, E>;
    pub fn spawn(self);
}

pub struct IntervalBuilder<U, E> { ... }

impl<U, E> IntervalBuilder<U, E>
where
    U: Send + Sync + 'static,
    E: Send + Sync + 'static,
{
    fn new() -> Self;
    pub fn options(mut self, opts: IntervalOptions<U, E>) -> Self;
    pub fn event(mut self, event: for<'a> fn(&'a Framework<U, E>) -> BoxFuture<'a, Result<IntervalNext, E>>) -> Self;
    pub fn build(self, framework: Arc<Framework<U, E>>) -> Interval<U, E>;
    pub fn spawn(self, framework: Arc<Framework<U, E>>);
}
```

**Comment by kangalio** [comment]
I appreciate your detailed design thoughts, but does this need to be built-in to poise directly? I feel like your Interval code should be adaptable to be a general purpose async utility crate.

On another note, what's the advantage of your API over a simple tokio::spawn-ed background task with a `loop` and a `tokio::time::sleep`?

**Comment by CraftSpider** [comment]
It may actually be good for a general-purpose crate, true. The usage of framework specifically could probably become a generic user-supplied datatype.

The implementation is built on top of `tokio::time::interval`, since it supplies the builtin handling of what happens when tasks run long, though without some of the bells and whistles this adds. The other advantages are largely around just adding the various callbacks - lets me do things like send messages or handle cleanup failures elegantly and with similar code to the framework's `on_error`. It's basically just a utility which handles some of the edge cases for the user.

**Comment by kangalio** [comment]
I'll close this because I believe intervals are a concept so general there's no one size fits all solution, and even if there is, it should not be in poise.

But you're encouraged to put the interval utility in a crate (you can keep the poise specific parts by having the crate depend on poise) and reuse the interval utility across your projects

**Comment by CraftSpider** [comment]
Sounds good. Thank you for the crate by the way - I'm rewriting a bot I originally wrote in Python in Rust, and `poise` has been great to work with.
