### ISSUE TITLE
How do i create mutable context or user data?

### ISSUE THREAD

**Issue by aalhitennf** [kangalioo/poise#134]
With serenity i add things with TypeMapKey etc but i couldn't find similar example or figure out same for poise. Should i just wrap user data to Arc<Mutex<_>>?  I played with that a little but that seems to trigger send + sync problems immediately.

**Comment by aalhitennf** [comment]
Simple example of my problem:  

main.rs
```
pub struct Cache {
    items: Vec<String>,
}


pub struct ContextData {
    cache: Mutex<Cache>,
}

...
.setup(...Box::pin...
    
    let cache = Mutex::new(Cache { items: vec![] });
    Ok(ContextData {  
      cache,
    })
)
```

command.rs
```
/// Search for a hero
#[poise::command(slash_command)]
pub async fn search(
    ctx: Context<'_>,
    #[description = "Search for thing"] name: String,
) -> ... {
     let cache = ctx.data().cache.lock().map_err(|e| anyhow!("asdfasdf"))?;
     let results = cache.search(&name);
     ...
}
```

This triggers error in `poise::command` macro 

```
future cannot be sent between threads safely
within `impl Future<Output = Result<(), FrameworkError<'_, ContextData, Box<dyn StdError + std::marker::Send + Sync>>>>`, the trait `std::marker::Send` is not implemented for `std::sync::MutexGuard<'_, cache::Cache>`
required for the cast from `impl Future<Output = Result<(), FrameworkError<'_, ContextData, Box<dyn StdError + std::marker::Send + Sync>>>>` to the object type `dyn std::future::Future<Output = Result<(), FrameworkError<'_, ContextData, Box<(dyn StdError + std::marker::Send + Sync + 'static)>>>> + std::marker::Send`
```

Sorry if this is messy and not understandable, im tired

**Comment by aalhitennf** [comment]
I also tried wrapping the mutex in arc, no difference

**Comment by kangalio** [comment]
Albeit confusing and verbosely worded, this is a common error message and it means "you cannot hold a std mutex lock across an await point".

This is for good reason, because locks should only be held for a short while and if the lock is held at an await point, where IO and other tasks are scheduled to run which can take a while, other tasks needing to lock the mutex are blocked.

The best solution is to restructure the code so the mutex lock is only held shortly and ends before the next `.await`. In your case `let results = ctx.data().cache.lock().map_err(...)?.search(&name);` (perhaps with `.clone()` at the end) should work, because the cache is not stored in its own variable anymore hence it becomes a so-called temporary and is dropped at the end of that line.

The easy solution is to use tokio::Mutex. This type _can_ be held across an await point, so your code would work as is. The issues with blocking other tasks still apply, though

**Comment by aalhitennf** [comment]
That makes sense, a lot. I guess blocking wont be big problem since the search task only takes few milliseconds to complete with my current amount of data. (i'll be crying later when it starts to become a problem) Thanks again :+1:

**Comment by kangalio** [comment]
> I guess blocking wont be big problem since the search task only takes few milliseconds to complete

The search task is not what's problematic; the `.await` statement later down in the code that you omitted from the code snippets is. Depending on what is being awaited, that may take up to a few seconds (for example a network request)

**Comment by aalhitennf** [comment]
I see, it was that part later on. Well those awaits can block a lot longer, and will cause a problem since there are some message sending, possible interactive discord messages etc. I guess i need to put my brain to work and figure out a different way. I sometimes use std::mem::drop on the mutex guard early and it has resolved some deadlocks but that didn't seem to have effect here.

**Comment by kangalio** [comment]
> I sometimes use std::mem::drop on the mutex guard early and it has resolved some deadlocks but that didn't seem to have effect here.

Yes, Rust unfortunately doesn't take `drop()` into account when analyzing how long an object lives. You need to use explicit scopes (`{}`) or temporaries instead. For example
```rust
let lock = mutex.lock();
let data = lock.get_data();
drop(lock);
do_something(data).await;
```
does not work but
```rust
let data = {
    let lock = mutex.lock();
    lock.get_data()
};
do_something(data).await;
```
or
```rust
let data = mutex.lock().get_data();
do_something(data).await;
```
does.

**Comment by aalhitennf** [comment]
Now that i clone the data from cache instead of returning references, it seems to be fine with this:  

```
let cache = ctx.data().cache.lock().await;
let data = cache.search()?; // Used to return Vec<&T>, now Vec<T>
std::mem::drop(cache);

somethingsomething(data).await;
```

**Comment by kangalio** [comment]
Interesting. Is the `drop(cache)` required to avoid compilation errors?

**Comment by aalhitennf** [comment]
> Interesting. Is the `drop(cache)` required to avoid compilation errors?

Nope, but not dropping the guard would cause cache mutex to be locked until all the awaits later is completed, causing problems? That has been the case with my other projects so i'm just applying same logic here: release the lock as early as possible so it will be ready for other calls/threads.
