### ISSUE TITLE
Rebase serenity-next

### ISSUE THREAD

**Issue by cheesycod** [kangalioo/poise#141]
Would be neat if serenity-next branch could be rebased on develop somehow

**Comment by cheesycod** [comment]
>

**Comment by kangalio** [comment]
![Screenshot_20230418_115218](https://user-images.githubusercontent.com/21220820/232740893-eeb9bda3-8c2a-49eb-b448-74903dc330b1.png)

\>.<

Beginning to think it's better to port develop to serenity-next from scratch

**Comment by jamesbt365** [comment]
Was resolved by #192 which was just merged, no idea if a different approach later would be better and this is staying open to track that?

**Comment by kangalio** [comment]
> Was resolved by #192 which was just merged, no idea if a different approach later would be better and this is staying open to track that?

Nah I just forgot
