### ISSUE TITLE
Unit testing example/functionality

### ISSUE THREAD

**Issue by dob9601** [kangalioo/poise#142]
Providing an example on how to unit test a bot would be useful. It might involve exposing some way to mock `ApplicationContext`.

So far, the only way to achieve testing is to define an inner function for every command and have that contain most of the functionality

**Comment by kangalio** [comment]
Unit testing a Discord bot is something I tried time and time again. It always ended up in the realization that mocking the Discord API is an uphill battle.

I now believe that the approach you mention (inner function) in the only real working approach. Would you still want to have an example for that?

**Comment by dob9601** [comment]
I think it could be useful - especially in terms of any calls to the methods of the context.

My main qualm is that having an inner function often isn't amazing for readability. One solution might be to conditionally expose the transformed function in the `Command` struct when `#[cfg(test)]` is enabled

**Comment by mazzi** [comment]
Hi people. Do you know if there's any plan to engage on this topic?
In my case, the goal would be to test commands. Mocking the context and some other things are involved for that
I've also tried some approaches and gets really hairy.
Thanks!
