### ISSUE TITLE
Document default_member_permissions

### ISSUE THREAD

**Issue by Astralchroma** [kangalioo/poise#145]

**Comment by Astralchroma** [comment]
seems to be `default_member_permissions`? but isnt documented on https://github.com/serenity-rs/poise/blob/bd7943feee76d381e637f4833d07aa831e8048a0/macros/src/lib.rs#L151 so I couldnt find it until looking deeper

**Comment by kangalio** [comment]
See https://github.com/serenity-rs/poise/pull/70 for why it's a separate field
