### ISSUE TITLE
Derive macro for Modal only supports string fields

### ISSUE THREAD

**Issue by drac-dot-gay** [kangalioo/poise#149]
According to discord's docs, modals support channel selects, user selects, etc. [(link)](https://discord.com/developers/docs/interactions/message-components)

However, currently the derive macro for modals only supports string inputs as far as I can tell. Am I missing something?

**Comment by kangalio** [comment]
I just tested; modals currently still only support text inputs.

`DiscordJsonSingleError { code: "UNION_TYPE_CHOICES", message: "Value of field \"type\" must be one of (4,).", path: "data.components.0.components.0" }`

Testing code: https://pastebin.com/XYPqS2KL
