### ISSUE TITLE
Add support for #[max] and #[min] for string command option types?

### ISSUE THREAD

**Issue by matteopolak** [kangalioo/poise#154]
Hey there!

It looks like there isn't support for restricting strings to certain lengths with the function parameter macros.
It's fairly similar to `min_value` and `max_value` for integers, but uses `min_length` and `max_length` (in the Discord API)

See: [api docs](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure)

Would it be possible to add support for this in the future? I haven't looked at the internals of this library but I can set up a PR for it if you don't have time.

**Comment by kangalio** [comment]
Sure! Would you prefer `#[min = ...]` and `#[max = ...]` or `#[min_length = ...]` and `#[max_length = ...]`?

**Comment by RGBCube** [comment]
min_len and max_len would be the best as the std uses len

**Comment by matteopolak** [comment]
> Sure! Would you prefer `#[min = ...]` and `#[max = ...]` or `#[min_length = ...]` and `#[max_length = ...]`?

I think `#[max_length = ...]` and `#[min_length = ...]` would make the most sense as it's referring to the bounds of the length attribute (as opposed to `#[max = ...]` which refers to the actual value)?

**Comment by kangalio** [comment]
@matteopolak Can you test the commit I just pushed?

You need to replace the poise dependency line in Cargo.toml with `poise = { git = "https://github.com/serenity-rs/poise" }`

**Comment by matteopolak** [comment]
Seems to be all working! I tested both of them by themselves and both of them together.

**Comment by kangalio** [comment]
Perfect. Released in 0.5.5
