### ISSUE TITLE
support for non-string select menus?

### ISSUE THREAD

**Issue by joel-olazagasti** [kangalioo/poise#160]
I've given a good scouring of the docs/examples, and I'm haven't found a pattern for creating any of the non-string select menus in a message component with Poise. Is that not supported in Poise at the moment or am I just missing it?

Those select menu types being:
- User
- Channel
- Role
- Mentionable

I see that the `SelectMenuOption` struct takes `Strings` for the label/value fields, but also that kangalio submitted a PR to Serenity to add support for those other menu types.

**Comment by kangalio** [comment]
Select menus in message components are the job of serenity, not poise. Poise is just the command framework built on top of serenity, but you still use serenity's facilities like its message builders.

I did add support for the other menu types, but for the next major version. It's not released yet, but you can browse the docs https://serenity-rs.github.io/serenity/next/serenity/builder/enum.CreateSelectMenuKind.html and if you want you can use poise's serenity-next branch to use the next major version now already (be aware of frequent breaking changes though!)

**Comment by joel-olazagasti** [comment]
Appreciate the swift response! Somehow I missed that the PR wasn't on the release branch. That does make it make sense why I couldn't find it in the docs. Dangers of coding late into the night. I'll shift over to the serenity-next branch and give it a shot!
