### ISSUE TITLE
`poise::command` should treat `r#move` and `r#loop` as valid command names without `r#`

### ISSUE THREAD

**Issue by fee1-dead** [kangalioo/poise#168]
Title. Currently using `serenity-next` branch so let me know if this has already been done. I'm currently making a music bot and `loop` and `move` are good command names that I cannot use :(

**Comment by kangalio** [comment]
The `#[rename = "..."]` attribute was made partly for this purpose.

But raw identifiers should still be supported so let's leave this issue open until that's implemented
