### ISSUE TITLE
question: dispatching to a Serenity EventHandler without cloning?

### ISSUE THREAD

**Issue by thetayloredman** [kangalioo/poise#171]
```rs
            event_handler: |ctx, event, _, _| {
                Box::pin(async move {
                    event.clone().dispatch(ctx.clone(), &Handler).await;
                    Ok(())
                })
            },
```

Is there a way to eliminate the clones here? Maybe an EventHandler that only takes references to ctx?

**Comment by kangalio** [comment]
It's not possible; EventHandler requires owned data.

By the way, you don't need to manually dispatch to EventHandler like this, you can register an EventHandler like in vanilla serenity by using `.client_settings()` on `FrameworkBuilder`

**Comment by thetayloredman** [comment]
> By the way, you don't need to manually dispatch to EventHandler like this, you can register an EventHandler like in vanilla serenity by using `.client_settings()` on `FrameworkBuilder`

I- thank you for catching that. I wasn't aware that existed. Thanks!
