### ISSUE TITLE
Add and create commands dynamically while framework is started?

### ISSUE THREAD

**Issue by aalhitennf** [kangalioo/poise#172]
Im trying to figure out if its possible to create command functions without restarting app/framework, i.e. http server/unix socket listening in another thread and interacting with framework. I can register a command with `Http::create_guild_application_command`, but haven't found out a way to interact with framework so i could somehow maybe also add the function to handle the command, so the registered command would actually also do something. Is this possible at all?

**Comment by aalhitennf** [comment]
I figured out a hacky way with event_handler and `poise::Event::InteractionCreate { interaction }`, it feels a bit wrong but works :shrug:. Quick demonstration:

```
        ...
        poise::Event::InteractionCreate { interaction } => {
            let i = interaction.clone();
            let cmd = i.application_command().unwrap();
            
           if cmd.data.name == "whatsup" {
               cmd.create_interaction_response(ctx, |r| {
                   r.interaction_response_data(|d| d.content("whassup"))
                }).await.unwrap();
           }
        }
        ...
```

**Comment by kangalio** [comment]
That is the best way to do it

**Comment by aalhitennf** [comment]
> That is the best way to do it  

Thanks for confirming :+1:
