### ISSUE TITLE
feature request: Add shortcut methods like `reply()` `reply_ping()` for `poise::Context`

### ISSUE THREAD

**Issue by B-2U** [kangalioo/poise#182]
Sometimes I just want to make a simple response to user and don't need a nested builder, how do you think about adding some shortcut methods like `reply()` `reply_ping()` which is in serenity context and take only a content argument?
![image](https://github.com/serenity-rs/poise/assets/82710122/a79ce5dd-0e77-4230-8a9d-40b1450afc6c)

if you like it too, I can try to make a PR

**Comment by kangalio** [comment]
There is already a shortcut method that only takes a content argument: `Context.say`. Are you suggesting to add a new variant of that method with `reply` set to `true`, analogous to serenity's reply_ping?

**Comment by B-2U** [comment]
>Are you suggesting to add a new variant of that method with `reply` set to `true`, analogous to serenity's reply_ping?

yes, that's exactly what I mean.

**Comment by kangalio** [comment]
I'm doubtful if it's useful; it can only be useful in prefix contexts anyways, and how often do you reply with a ping anyways? If you just generally prefer replies to ping the user, that's fine, but then the better way to accomplish that is by making your own reply function which sends replies in all the ways you like best; or use reply_callback alternatively.

But on the other hand there may be good use cases I didn't think of, and adding a new method to the pile of pre-existing Context methods is low-rise, so I'm open for feedback :)

**Comment by B-2U** [comment]
ping or not isn't really the case, I'm more focusing on `reply`

for my own use cases, i would like my command which works in both slash and prefix act similar in same code, 
so when the bot *respond* in interactions, for me the corresponding method in prefix should be *reply*
but currently there's only `say` under the poise::context. it works well for interaction, but for prefix commands simply send a message in same channel will be confused to other users in my opnion

although I do can use `reply_callback` invoke to add `reply(true)` for every `poise::context.say`, but it might also effect some rare condition that just want to send a message without replying

**Comment by kangalio** [comment]
Alright, I'd be open to a PR then
