### ISSUE TITLE
Request: Example of event_handler

### ISSUE THREAD

**Issue by keiveulbugs** [kangalioo/poise#188]
Hi!

Looking at the Discord, almost every week someone asks about an explanation on how the event_handler works.

Would it be a good idea to just make an example using the event_handler where it is used to collect messages, message updates and so on?

**Comment by iTrooz** [comment]
I just came to the issue tracker to ask about this.
I think this is a good idea

**Comment by kangalio** [comment]
I agree, I'm open to PRs

**Comment by gkuznik** [comment]
There already is a very basic example in [basic_structure](https://github.com/serenity-rs/poise/blob/current/examples/basic_structure/main.rs#L77-L81).
Nonetheless, I think having an explicit example is good. I have proposed one in #199
