### ISSUE TITLE
CollectComponentInteraction is failing on the first interaction for every message.

### ISSUE THREAD

**Issue by taimurey** [kangalioo/poise#193]
The CollectComponentInteraction isn't functioning correctly. The initial interaction consistently fails.

```rust
if let Some(mci) = CollectComponentInteraction::new(ctx.clone())
    .message_id(message_id)
    .filter(|_| true)
    .await
{
```

However, when utilizing a Message component, the interaction doesn't fail:

```rust
if let Interaction::MessageComponent(button) = &interaction {
```

**Comment by scottbot95** [comment]
`CollectComponentInteraction` is a feature from [serenity](https://github.com/serenity-rs/serenity) itself, not `poise` which is built on top of `serenity`. This issue would likely be better served in the serenity repo.

----

That said, what do you mean by it "consistently fails"? That you get something like this in Discord? 
<img width="139" alt="image" src="https://github.com/serenity-rs/poise/assets/2055068/ded708fd-571f-4cb2-bc4b-85986451ea43">

If so, Discord requires that interactions are "acknowledged". This can be done by creating a follow up, editing the original message, or sending a `DEFERRED_UPDATE_MESSAGE` response. `CollectComponentInteraction` will do none of these by default so it is on you to respond to the interaction somehow. I'm not sure how you're acquiring a reference to an `Interaction` in your second case, but is it possible that you're acknowledging the interaction somehow in that case?

**Comment by kangalio** [comment]
I think @taimurey may be hitting the issue that I fixed here: https://github.com/serenity-rs/serenity/pull/2388

That fix will be released with the next major version of serenity

**Comment by GnomedDev** [comment]
This has been fixed upstream.
