### ISSUE TITLE
Has `add_string_choice` support been implemented?

### ISSUE THREAD

**Issue by nabakin** [kangalioo/poise#2]
Looking through the code, it doesn't seem like support for `add_string_choice` has been implemented. Is this correct or have I missed it? I'd like to give users choices when entering slash commands.

**Comment by kangalioo** [comment]
There's no built-in support for that. I'm not yet sure how to design the API for that. It would probably be some form of derive macro on a macro i.e.
```rust
#[derive(poise::StringChoice)]
enum MyChoice {
    #["The first choice"]
    ChoiceA,
    #["The second choice"]
    ChoiceB,
}
```
but maybe it would be smarter to reuse an existing enum derive crate like strum.

In any case, it should be possible to cobble a working string choice type together right now by implementing PopArgument and SlashArgument. I can make an example if you want

**Comment by nabakin** [comment]
I'd appreciate that. I was looking into implementing the functionality myself, but Rust macros are so complex. Having a starting point would be helpful.

**Comment by kangalioo** [comment]
Are you referring to implementing PopArgument and SlashArgument, or to adding the StringChoice derive macro to poise itself?

**Comment by nabakin** [comment]
Oh I thought PopArgument and SlashArgument had to do with poise itself and implementing StringChoice. Re-reading what you sent, I understand what you mean. If you can give me an example string choice implementation with PopArugment and SlashArgument, that would be perfect.

**Comment by kangalioo** [comment]
I'll only have time in 6 hours from now, I'll make an example then probably :) Will also probably look into adding something like a StringChoice derive macro, I decided on a design after thinking about it for a bit

**Comment by nabakin** [comment]
No rush! Appreciate the help

**Comment by kangalioo** [comment]
Here's an example https://github.com/kangalioo/poise/blob/107fdcc5ff192aa940b0493562c0ab69e741b674/examples/main.rs#L83-L153

You currently need to use poise::Wrapper because otherwise there'd be overlapping blanket implementations (`impl<T: PopArgument> PopArgumentAsync for T` and `impl<T: serenity::ArgumentConvert> PopArgumentAsync for T`). This annoyance will probably be removed at some point though, using [Lukas Kalbertodt's specialization trick](https://lukaskalbertodt.github.io/2019/12/05/generalized-autoref-based-specialization.html).

**Comment by nabakin** [comment]
For some reason, I'm getting this error when using your code and running the command.
```
Error in slash command "choice": Bot author did not register their commands correctly (a required argument is missing)
```
I'm not sure what the problem is. I tried changing the `CreateApplicationCommandOption` and tracing the code but couldn't figure it out. It must have something to do with this macro since it's what triggers the error.
```rust
// Extract T
($ctx:ident, $guild_id:ident, $channel_id:ident, $args:ident => $name:ident: $($type:tt)*) => {
    $crate::_parse_slash!($ctx, $guild_id, $channel_id, $args => $name: Option<$($type)*>)
        .ok_or($crate::SlashArgError::CommandStructureMismatch("a required argument is missing"))?
};
```
Is `poise::Wrapper` breaking something?

Also, is there a way to set these commands as guild commands? It takes awhile for the slash command interface in discord to update.

**Comment by nabakin** [comment]
Never mind, I figured out the answers to all of those questions when I copied and ran your `register` command. Now, unfortunately, I have a different issue where the choices won't show up (I can still enter them and they work) and the `serenity::User` type is resulting in the error.
```
Error in slash command "id": Failed to parse argument: User not found or unknown format
```
I'm in the process of working through these atm.

**Comment by kangalioo** [comment]
> the choices won't show up (I can still enter them and they work)

I don't understand. How can you enter choices if they don't exist in the Discord UI?

> `Error in slash command "id": Failed to parse argument: User not found or unknown format`

The [string parsing code for User](https://github.com/serenity-rs/serenity/blob/e87293eccbee6c8c04b92c552a99eb654a6d81bd/src/utils/argument_convert/user.rs#L37-L64) currently only checks serenity's cache for users. However, that cache is only filled if the GUILD_PRESENCES intent is enabled for the bot. Could you try enabling that intent? Alternatively, you could use Member, which always works (it only searched current guild though).

I don't really know which way to find users globally would be better, else I'd have made a PR to serenity already.

**Comment by nabakin** [comment]
> I don't understand. How can you enter choices if they don't exist in the Discord UI?

As if they are a normal string without choices like so:
![image](https://user-images.githubusercontent.com/894305/130330215-b6301c68-3a31-422e-9d4a-a9b7eecabdf1.png)

The choice UI should look like this:
![image](https://user-images.githubusercontent.com/894305/130330238-03933c1a-bd51-4204-8090-53a4aef43538.png)

> The string parsing code for User currently only checks serenity's cache for users. However, that cache is only filled if the GUILD_PRESENCES intent is enabled for the bot. Could you try enabling that intent? Alternatively, you could use Member instead of User, which always works (it only searches current guild though).

Ah, that's probably the problem. I've since been able to get it to work but sometimes it works and sometimes it doesn't. I've noticed it doesn't work if I haven't sent a message in the server for awhile which would be inline with it not being in serenity's cache. The bot has the administrator permission at the moment so I think that means it has every intent.

Good to know about Member, I'll try it the next time I run into the bug.

**Comment by nabakin** [comment]
Fyi, copying and compiling your choice example code verbatim doesn't show the choice UI.

![image](https://user-images.githubusercontent.com/894305/130332552-57c4f876-77d5-4785-b8fe-da68003a717e.png)

**Comment by kangalioo** [comment]
Could you update poise? `cargo update -p poise` I could imagine that cargo didn't automatically didnt include a fix I had to push for choices to work properly

**Comment by nabakin** [comment]
Thank you! That was my problem. Such a simple thing, I didn't realize you changed poise to make it work.

**Comment by kangalioo** [comment]
I added the derive macro :)

https://github.com/kangalioo/poise/blob/d3b240c2965b72d6f00d661e344a9da7222edb21/examples/main.rs#L83-L101
