### ISSUE TITLE
 CreateReply does not contain set_embed/set_components [SOLVED]

### ISSUE THREAD

**Issue by RoFred2** [kangalioo/poise#228]
The title says it all.

**Comment by kangalio** [comment]
`set_components()` exists and is called `components()` (or what behavior would you expect from a method called `set_components`)?

`set_embed` indeed does not exist.. But I don't see what to use it for? I assume it would set a single embed, overwriting any previous embed. But why would you have a previous embed in a blank CreateReply builder? And without a previous embed, you can just use `.embed()`

Or did you mean `set_embeds` (plural)? That would be the most sensible of these three in my opinion, but I'm still unsure it is needed. `create_reply.embeds = ...` exists. It is not chainable, but are there cases where you want chainability but cannot use `.embed()`?

**Comment by RoFred2** [comment]
> `set_components()` exists and is called `components()` (or what behavior would you expect from a method called `set_components`)?
> 
> `set_embed` indeed does not exist.. But I don't see what to use it for? I assume it would set a single embed, overwriting any previous embed. But why would you have a previous embed in a blank CreateReply builder? And without a previous embed, you can just use `.embed()`
> 
> Or did you mean `set_embeds` (plural)? That would be the most sensible of these three in my opinion, but I'm still unsure it is needed. `create_reply.embeds = ...` exists. It is not chainable, but are there cases where you want chainability but cannot use `.embed()`?

I had the impression that .embeds would ADD to the current embeds instead of overwriting them, .components likewise. My bad

**Comment by kangalio** [comment]
Mind the plurals, please :grinning: it gets confusing otherwise

> I had the impression that .embeds would ADD to the current embeds instead of overwriting them, .components likewise. My bad

`.embeds()` does not exist! `.embed()` _does_ exist!

And yeah, the docs about `.embed()` and `.components()` are also relatively clear about their respective behavior:

![Screenshot_20231129_204824](https://github.com/serenity-rs/poise/assets/21220820/ecc505a8-3255-439a-98a3-808359a84b01)
