### ISSUE TITLE
0.6.0 not on crates.io yet

### ISSUE THREAD

**Issue by willfindlay** [kangalioo/poise#229]
Latest reported version is 0.5.7 according to crates.io

**Comment by jamesbt365** [comment]
Not really a bug as it is kinda intended, 0.6.0 was never released on crates.io because too many large issues appeared after rebase, including argument parsing which completely makes the bot unusable in some cases.

**Comment by willfindlay** [comment]
Ah, I see. Was missing that context, thanks.
