### ISSUE TITLE
Add support for integer and double option choices.

### ISSUE THREAD

**Issue by bavalpey** [kangalioo/poise#230]
According to [the discord API](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-choice-structure), paramater choices can be string, integer, or doubles for parameters that are registered as ``STRING, INTEGER, or NUMBER``.

There is currently *no* way to register options in.

What I would like to see is support for this, ideally in the same form as entering descriptions.

```rs
#[poise::command(slash_command)]
async fn my_method(
    ctx: Context<'_>,
    #[description = "Description"] // This form is great and easy to use.  Why make it cumbersome with the enum form?
    #[choices = (1u8, 2u8, 3u8, 4u8, 5u8, 9u8)] name: u8, // tuple works best
) -> Result<(), Error> {
  // ...
}
```

**Comment by kangalio** [comment]
The syntax should be `#[choices(1, 2, 3, 4, 5, 9)] name: u8`, but I agree this is a good feature. It should work for all types that implement Display and can be parsed from a literal token

I'm just not quite sure how the macro should handle the types. Like
```rust
type MyInt = u32;
#[poise::command]
async fn my_method(ctx: Context<'_>, #[choices(1, 2, 3, 4, 5, 9)] name: MyInt)
```
The macro only sees ambiguous integer literals and "MyInt"

**Comment by kangalio** [comment]
Having written that code snippet out, it doesn't seem hard anymore lol. The macro can generate the string labels with `$value.to_string()` and dispatch from the choice index to the value with a match statement `match index { 0 => $value0, 1 => $value2 }`; and as the type it can just use literally `MyInt` everywhere. That should work

**Comment by kangalio** [comment]
The devil is being in the details, as always

**Comment by kangalio** [comment]
I've implemented this in the inline-choice branch, could I interest you in trying it out / testing it?

**Comment by bavalpey** [comment]
> I've implemented this in the inline-choice branch, could I interest you in trying it out / testing it?

Yup! I'll test it here in a moment.

**Comment by bavalpey** [comment]
This works great!

**Comment by kangalio** [comment]
That's fun to hear, if you knew the messy data flow I've had to wedge into to implement this :D But great then. I suppose we can close the issue and release, then?

**Comment by bavalpey** [comment]
Works for me!
