### ISSUE TITLE
docs 404

### ISSUE THREAD

**Issue by Yarn** [kangalioo/poise#24]
the docs link https://kangalioo.github.io/poise/poise/ is broken

**Comment by kangalioo** [comment]
Oh no I was hoping I'd get around puhsing some commit to master (to make it rebuild the master docs) soon enough so no one would notice :smile:

Sorry for the 404, I'll push a dummy commit to master to rebuild the docs (now with method usage scraped from examples!)

**Comment by kangalioo** [comment]
Okay nevermind, upstream serenity next branch has a breaking change that breaks build, this has to wait until I get home from school

**Comment by kangalioo** [comment]
Fixed, https://kangalioo.github.io/poise/ is now viewable
