### ISSUE TITLE
Atomics - Should this be fetch_add?

### ISSUE THREAD

**Issue by c-git** [kangalioo/poise#245]
I was reading one of the examples and I saw what looked like code that could result in a race condition but I haven't worked with atomics much so I may be mistaken. I'm just raising it in case someone who knows more than me could take a look. Based on my understanding [this code](https://github.com/serenity-rs/poise/blob/f6b94ca83bc9f98815112456adab0d3031e37319/examples/event_handler/main.rs#L60) could read the value increment it and then before it writes it back it gets incremented somewhere else and the increment is lost. Might be better to use [fetch_add](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html#method.fetch_add) to increment the value in an "atomic" way. Let me know if that makes sense I should be able to do a PR quickly to fix it.

**Comment by kangalio** [comment]
Ah, that sounds correct. Yeah, feel free to make a PR :+1:

**Comment by c-git** [comment]
Great created the PR, as I'd already tried making the changes. Still need to test it.
