### ISSUE TITLE
Cannot use any parameters in context menu function

### ISSUE THREAD

**Issue by nwerosama** [kangalioo/poise#256]
Hi, I don't know what the issue is, maybe I am bad at giving the parameter it needs or.. I don't know.. I did double-check the [example file](https://github.com/serenity-rs/poise/blob/3eef3f4fa06cf12e46a2d50b3b4c8375e8781ef4/examples/feature_showcase/context_menu.rs) and still the same result.
![image](https://github.com/serenity-rs/poise/assets/96593068/555cebfd-b4f3-485c-92b7-288fa9da14e9)

If I insert any parameter or play around with the "<>" thingy, still says the same error message.
Tried restarting `rust-analyzer` extension and reloading the VSCode window, still nothing.

I assume the examples has gone outdated or my misunderstanding.
I am using Rust 1.77 with Poise 0.6.1

**Comment by kangalio** [comment]
There needs to be an additional parameter beyond the obligatory Context parameter. I admit, the error message is quite ambiguous here

**Comment by nwerosama** [comment]
Can you please explain more? Also, I did try to test the example echo function but replacing the Context with `poise::Context` and `serenity::Message` with `poise::serenity_prelude::Message`, and this is the result..
![image](https://github.com/serenity-rs/poise/assets/96593068/6ddf75cf-acd6-4660-8584-419514b1e1a0)

**Comment by nwerosama** [comment]
Actually nevermind, I am stupid. It seems to work now.
