### ISSUE TITLE
PopArgumentAsync isn't real

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [kangalioo/poise#257]
the docs mention `PopArgumentAsync`:

![image](https://github.com/serenity-rs/poise/assets/14184826/06fc142d-84d9-4e17-b17b-ccd6f7a2517c)

but it doesn't exist:
![image](https://github.com/serenity-rs/poise/assets/14184826/57cdc225-24e2-4068-b3dd-de0ee9f91e13)

the regular `PopArgument` trait is already async.

**Comment by GnomedDev** [comment]
Fixed in 2100c0072da7a3e072d7a4ee8119b1a76077c53a.
