### ISSUE TITLE
ArgumentParse errors from poise::command are not sanitized

### ISSUE THREAD

**Issue by getchoo** [kangalioo/poise#263]
https://github.com/serenity-rs/poise/blob/186897a2f4f18b59152c9e670db5cd328bb22ea7/src/builtins/mod.rs#L86-L90

this can easily lead to many side effects with not-very-specially formatted messages like
> hello\` <@746501080409702461> `world

**Comment by jamesbt365** [comment]
Could be easily fixed by disabling all mentions.
