### ISSUE TITLE
Allow to provide a set of Team Roles, to be added to the owner array 

### ISSUE THREAD

**Issue by C0D3-M4513R** [kangalioo/poise#265]
Depends on https://github.com/serenity-rs/serenity/issues/2859
Ref.:
- https://serenity-rs.github.io/poise/current/poise/structs/struct.FrameworkOptions.html#structfield.initialize_owners
- https://discord.com/developers/docs/topics/teams#team-member-roles-team-member-role-types

It would be nice, if I could just specify a set/list of Team Roles.
Every member of the owning Team, with one of those roles would get added to the internal owner list.

Also it would be nice, if there was an option to only consider accepted Team Members for the default initialization. 

e.g. `Http::get_current_application_info()` -> `If a Team, get Team Members` -> `Filter to only Accepted Team Members` -> `Filter to only Admins/Developers`.

**Comment by C0D3-M4513R** [comment]
I don't see a way to filter to only Accepted Team Members with #278 ?

**Comment by GnomedDev** [comment]
See https://discord.com/developers/docs/topics/teams#team-member-roles, add the users who you want to be treated as "owners" to the bot's team on the developer portal, set the permission level you want them to have, and set that permission level in `FrameworkOptions::initialized_team_roles`.
