### ISSUE TITLE
macro to quickly add commands as-is

### ISSUE THREAD

**Issue by s0lst1ce** [kangalioo/poise#28]
What do you think about introducing a macro like the following:
```rs
macro_rules! add_commands {
    ($framework_builder:ident, $($command:path),*) => {{
        $($framework_builder = $framework_builder.command($command(), |f| f);)*
        $framework_builder
    }};
}
```
This would allow one to do: 
```rs
let mut framework_builder = poise::Framework::build();
framework_builder =  add_commands!(
        framework_builder,
        help,
        register,
        command1,
        command2
    );
let framework = framework_builder.build().await.unwrap();
```
This is what I currently do with my bot to cut down on the number of `.command(command1, |f| f)` calls. This would fit well alongside the already existing `builtins` I think.

**Comment by kangalioo** [comment]
Interesting idea. Alternatively, what do you think about a simple function on FrameworkBuilder instead?

```rust
let framework = poise::Framework::build()
    .commands([
        help,
        register,
        command1,
        command2,
    ])
    .build().await
    .unwrap();
```

**Comment by s0lst1ce** [comment]
I think that's better yes.

**Comment by kangalioo** [comment]
How's this? https://kangalioo.github.io/poise/develop/poise/struct.FrameworkBuilder.html#method.commands

**Comment by s0lst1ce** [comment]
Looks good to me.

**Comment by kangalioo** [comment]
👌
