### ISSUE TITLE
`FrameworkError::ctx` returns `None` for many variants

### ISSUE THREAD

**Issue by npry** [kangalioo/poise#295]
Currently `FrameworkError::ctx` has the following `match` case, despite the fact that some of these variants have an associated `ctx`:

```rust
pub fn ctx(&self) -> Option<crate::Context<'a, U, E>> {
    Some(match *self {
            // ...
            Self::Setup { .. }
            | Self::EventHandler { .. }
            | Self::UnknownCommand { .. }
            | Self::UnknownInteraction { .. }
            | Self::NonCommandMessage { .. }
            | Self::DynamicPrefix { .. } => return None,
    })
}
```

This was unexpected &mdash; Is there a reason?

 My `on_error` handler looks like:

```rust
if let Some(ctx) = err.ctx() {
    // notify the user something has gone wrong
    // presence of ctx suggests the error arose in response to a comamnd
} else {
    // no message context available, can't/not appropriate to notify user
    warn!("error had no context!");
}
```

**Comment by GnomedDev** [comment]
Their `ctx` is not a `poise::Context`, it is a `serenity::client::Context`.

**Comment by npry** [comment]
Whoops, just realized it's not all of them &mdash; however, several of them do have one, e.g. `UnknownInteraction`, `UnknownCommand`, which are what I need

**Comment by npry** [comment]
Oh, nvm, understood &mdash; what I'm looking at is the framework context. Sorry for live-rubber-ducking this.
