### ISSUE TITLE
Allow for custom slash command descriptions & different command names

### ISSUE THREAD

**Issue by Neutrovertido** [kangalioo/poise#296]
As title says, there is no easy way to set the slash command descriptions using poise if there is even any at all
![image](https://github.com/user-attachments/assets/68987530-a261-4bd4-85d5-4cd052f8a035)
It will always read "a slash command"

Also there is no way to rename a command, this would prove useful when we need the command to have a different name or when it should start with a number:
![image](https://github.com/user-attachments/assets/f7b8fb26-ebe9-4307-84a6-1e4c390c4f5d)

**Comment by anden3** [comment]
```rs
/// Roll an 8-ball.
#[poise:::command(rename = "8ball")]
pub async eightball(ctx: Context<'_>) -> Result<(), Error> {
    ctx.say(get_random_phrase()).await?;
    Ok(())
}
```

From: https://docs.rs/poise/latest/poise/macros/attr.command.html

> Documentation comments are used as help text. The first line is a single-line description, displayed in listings of your bot’s commands (i.e. `~help`). Following paragraphs are detailed explanations, for example for command-specific help (i.e. `~help command_name`). Escape newlines with `\`

> `rename`: Choose an alternative command name instead of the function name

**Comment by Neutrovertido** [comment]
Yeah, that did the trick. Didn't arrive at that page in the documentation after searching for a while. Sorry about pointless issue.
