### ISSUE TITLE
[Feature Request] bot_required_permissions in `poise::command`

### ISSUE THREAD

**Issue by Gnome-py** [kangalioo/poise#30]
## Summary

This would allow definition of the permissions the bot user must have for a command to execute, if not met, pass an error to on_error.

## Usecase
In order to reduce 403s in the command body, or repeated code to handle checking permissions and displaying friendly errors, it would allow the user to centralize it in on_error. I personally use `discord.py`'s `@commands.bot_required_permissions` extensively to define basic permissions such as send_messages, embed_links, or similar.

**Comment by kangalioo** [comment]
Implemented in 68b42d705045aec410191523522ff89afcffd7b1 (and a few subsequent commits)
