### ISSUE TITLE
Programmatically Invoke a Command with Custom Context

### ISSUE THREAD

**Issue by Cikmo** [kangalioo/poise#307]
I’m trying to figure out how to invoke a command programmatically. Is there a relatively simple way to do this currently, or would I need to create a workaround?

Use Case Example:
Let’s say I have a command that allows users to create buttons. When a user clicks a button, it should invoke a specified command. I’d like to be able to pass in the relevant context programmatically (e.g., the channel, user, etc.) so the command can execute with that context.

Is there a built-in way to do this, or should I consider hacking something together?

**Comment by Cikmo** [comment]
I didn't mean to close this 🤦

**Comment by jamesbt365** [comment]
Then reopen it?

**Comment by jamesbt365** [comment]
Commands can't exactly invoke each other, however you can move the logic of a command into another function that takes the `Context` and arguments from the command. Like this:

```rs
#[poise::command(prefix_command, hide_in_help)]
pub async fn functiona(ctx: Context<'_>) -> Result<(), Error> {
    functionb(ctx).await
}

pub async fn functionb(ctx: Context<'_>) -> Result<(), Error> {
    // do stuff here.

    Ok(())
}
```

**Comment by Cikmo** [comment]
> Then reopen it?

I don't have permission to do that, sorry about that.

**Comment by jamesbt365** [comment]
You did, if **you** close an issue you have the permission to reopen it. Its right next to the comment button.

**Comment by Cikmo** [comment]
> You did, if **you** close an issue you have the permission to reopen it. Its right next to the comment button.

Weird, didn't show for me.

Anyways, I guess your solution is the simplest workaround. I tried playing around with dispatch and message event and stuff, but it got pretty complicated mocking the context for both text commands and interactions. Thanks.
