### ISSUE TITLE
How to programmatically Invoke a Command with Custom Context

### ISSUE THREAD

**Issue by Cikmo** [kangalioo/poise#308]
I’m trying to figure out how to invoke a command programmatically. Is there a relatively simple way to do this currently, or would I need to create a workaround?

**Use Case Example:**
Let’s say I have a command that allows users to create buttons. When a user clicks a button, it should invoke a specified command. I’d like to be able to pass in the relevant context programmatically (e.g., the channel, user, etc.) so the command can execute with that context.

Is there a built-in way to do this, or should I consider hacking something together?

**Comment by jamesbt365** [comment]
Lets not open multiple issues for one thing please.
