### ISSUE TITLE
the serenity_prelude old serenity_prelude contains `#[repr(packed)]` structs which derive Debug, Eq and Cmp, and is thefore unsound

### ISSUE THREAD

**Issue by vrtgs** [kangalioo/poise#331]

**Comment by jamesbt365** [comment]
Proof? What are you looking at that indicates this is unsound?

Also if you're on about serenity_prelude (which is a reexport of serenity::all, you likely have opened this on the wrong repository)

**Comment by GnomedDev** [comment]
The issue author has said off-platform that they are unsure, so in combination with this being the wrong repo to open the issue on and extensive testing being done to make sure this is fine, I'm closing this issue.
