### ISSUE TITLE
Accessing message attachments from a command

### ISSUE THREAD

**Issue by zedseven** [kangalioo/poise#4]
Is it possible to access message attachments from within a command (using `PoiseContext`)?

I took a look through the available API and didn't see anything, but perhaps I missed something.

**Comment by zedseven** [comment]
Never mind, I just had to look at specifically the prefix context (since slash commands can't carry attachments), and the attachment info was in the message.

Sorry for creating a pointless issue, and thank you for your work on the library.

**Comment by kangalioo** [comment]
I'm glad you were able to find it :)

Btw I recently wrote a bit more documentation in the README, in case you haven't seen it
