### ISSUE TITLE
owners including users not specified in options is surprising (and feature request to be able to change behavior)

### ISSUE THREAD

**Issue by Yarn** [kangalioo/poise#40]
The docs on owners i can find are

https://kangalioo.github.io/poise/master/poise/attr.command.html
owners_only: Restricts command callers to the list of owners specified in framework options

https://kangalioo.github.io/poise/master/poise/struct.FrameworkOptions.html#structfield.owners
User IDs which are allowed to use owners_only commands

I think in both of these places it would probably be good to mention it adds the user that created the bot if it's not in owners already.

It would also be nice to have the option to disable that functionality.
https://kangalioo.github.io/poise/master/src/poise/framework/builder.rs.html#164

**Comment by kangalioo** [comment]
That's fair, sorry for the trouble.

Fixed in 271877e1ff5ef9f5d0369e4f2786a9744069f763. You can now do `.initialize_owners(false)` in the framework builder to disable this behavior
