### ISSUE TITLE
Adding a License

### ISSUE THREAD

**Issue by DrBluefall** [kangalioo/poise#5]
Because of the situation I'm working in, a library not having a LICENSE generally stokes concerns over whether or not it's fair game to use (since we're developing in a professional context).

So adding a LICENSE file would probably be helpful.

**Comment by kangalioo** [comment]
Done

> we're developing in a professional context

Keep in mind this library is currently in a volatile state. For example there recently was a large sweeping rename of many public items from `slash` to `application` as part of the context menu command feature

**Comment by DrBluefall** [comment]
Well, it's mostly because we're trying to look around for a good discord library that works with application commands (because of dpy becoming defunct). And considering the alternative is C++... I'm sort of rooting for Poise.
