### ISSUE TITLE
Help needed/Problem with registering songbird as VoiceGatewayManager

### ISSUE THREAD

**Issue by Nirusu99** [kangalioo/poise#50]
I'm certain that this problem is because of my lack of understanding rust that's why I'm sry for being so impudent to open an issue. 

I wanted to use [Songbird](https://docs.rs/songbird/latest/songbird/) alongside poise to handle voice for discord, but Songbird needs to be registered at startup as [VoiceGatewayManager](https://docs.rs/serenity/0.10.10/serenity/client/bridge/voice/trait.VoiceGatewayManager.html) which is done with [ClientBuilder#voice_manager_arc](https://docs.rs/serenity/0.10.10/serenity/client/struct.ClientBuilder.html#method.voice_manager_arc).  The method expects a struct with `poise::serenity_prelude::VoiceGatewayManager` implemented but [Songbird](https://docs.rs/songbird/latest/songbird/struct.Songbird.html) doesn't use the re-exports and implements `serenity::client::bridge::voice::VoiceGatewayManager`. I also had to enable the feature `voice` for serenity in poise to be able to use [ClientBuilder#voice_manager_arc](https://docs.rs/serenity/0.10.10/serenity/client/struct.ClientBuilder.html#method.voice_manager_arc).

Is there a simple way to tell the compiler that `poise::serenity_prelude::VoiceGatewayManager` and `serenity::client::bridge::voice::VoiceGatewayManager` are the same?

**Comment by kangalioo** [comment]
There seem to be two different versions of serenity in your program. Poise depends on the GitHub version of serenity (not for long, hopefully), while Songbird depends on the crates.io release. That's why the types are not compatible; they're from different crate versions.

Try replacing Songbird's crates.io serenity dependency with the GitHub version via [`[patch]` in the Cargo.toml](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html). Something like this:

```toml
[patch.crates-io]
serenity = { git = 'https://github.com/serenity-rs/serenity', branch = 'next' }
```

**Comment by Nirusu99** [comment]
Ah that makes so much sense now. Sadly with the patch songbird doesn't compile anymore, but using the [next branch of Songbird](https://github.com/serenity-rs/songbird/tree/next) fixed the whole issue for me because it also depends on the the `next` branch of serenity. 

```toml
[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "next"
features = [...]
```

From the errors I'd have never expected this to be a version problem. Thank you so much.
