### ISSUE TITLE
None of the commands specified work, `Ready` shows the server I am testing in is "Unavailable"

### ISSUE THREAD

**Issue by Kirottu** [kangalioo/poise#52]
That is about it, the `Ready` value in `user_data_setup` which I presume could be used for a ready function to report that the bot has logged in, has the guild I am testing in reported as unavailable like this:
```
guilds: [UnavailableGuild { id: GuildId(<The id for the guild>), unavailable: true }]
```
With the serenity standard framework this worked fine. Also it is not only slash commands that do not work, I can not use the `register` provided by examples or `help`.

**Comment by kangalioo** [comment]
Can you test with vanilla serenity on the next branch (what poise uses, [cargo docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)) whether the guild is shown as unavailable in the Ready event too?

The latest serenity version on the next branch switched to a new Discord API version (v10), which might be the cause of your problem

**Comment by Kirottu** [comment]
That does seem to be the issue yes, after getting my project to compile for the next branch it gives the same UnavailableGuild output and I can not run any of the commands.

**Comment by Kirottu** [comment]
And I pressed the wrong button. Good job me.

**Comment by kangalioo** [comment]
Can you create an issue on the serenity repository? This issue seems to be outside poise's control

**Comment by Kirottu** [comment]
Yeah I guess I will do that, thank you anyway! Now closing for real.
