### ISSUE TITLE
Unexpected token `include_str`

### ISSUE THREAD

**Issue by MrDogeBro** [kangalioo/poise#6]
Hey so I just updated my packages and poise updated as well. However, now that I've done that, whenever I try and run the bot the following error comes up and stops it from running...

```
error: unexpected token: `include_str`
 --> /Users/user/.cargo/git/checkouts/poise-2ca7e75d46548da7/435cf20/src/lib.rs:1:10
  |
1 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `poise`

```

Any help would be greatly appreciated. Thanks!

**Comment by kangalioo** [comment]
Could you update your Rust install?

That nice feature, which allows you to reuse README.md as crate documentation in rustdoc, has only been available since Rust 1.54

**Comment by MrDogeBro** [comment]
I see....however, in my opinion poise should have very similar requirements (especially in rust version) if not identical to the base crate, serenity, since it is meant to go on top of serenity. That's just my opinion tho.

Either way, this change should be documented.

**Comment by kangalioo** [comment]
Sorry for the churn, yeah there's an argument to be made that poise should have the same MSRV (minimum supported rust version) as serenity. Actually, GitHub CI checks MSRV in the repo, but it only runs after commiting.

Do you think I should develop in a separate branch (`develop`) and only merge to master every once in a while when CI passes, documentation is up to date etc?

> Also, what is that supposed to provide documentation for?

The README.md I recently updated contains a lot of information about library usage, like a quick start, documentation of the command macro, and other stuff. I think it's valuable to show that information not just in the GitHub repository but also in rustdoc

**Comment by MrDogeBro** [comment]
No worries your fine. I just feel like since its built on top of serenity it should have the same MSRV as serenity as it is the base. I also feel that would just make issues like this not be confusing/not pop up but that's my opinion and its your crate so do whatever you think is best and I'll still use the library either way lol. Just if the MSRV is going to be different that should probs be obvious in the docs/readme and all.

> Do you think I should develop in a separate branch (develop) and only merge to master every once in a while when CI passes, documentation is up to date etc?


> The README.md I recently updated contains a lot of information about library usage, like a quick start, documentation of the command macro, and other stuff. I think it's valuable to show that information not just in the GitHub repository but also in rustdoc

Ok makes sense — can see how that can be useful.

**Comment by kangalioo** [comment]
The project now compiles on its MSRV (1.48) again. I also started using a develop branch. This issue can be closed I think

**Comment by MrDogeBro** [comment]
Yup sounds good. Thanks.
