### ISSUE TITLE
Using custom event handling

### ISSUE THREAD

**Issue by Kirottu** [kangalioo/poise#62]
Adding the custom event handler itself seems to work fine, but the problem arises when I need to use some of the values in the `Data` struct. Namely a connection to a database. I need the connection to the database to be available for both commands and said interactions, and with using serenity's TypeMap for storing it would mean I would need to store it 2 times. Is there any other way to do this?

**Comment by kangalioo** [comment]
You can handle events using the listener callback https://kangalioo.github.io/poise/master/poise/struct.FrameworkOptions.html#structfield.listener

**Comment by Kirottu** [comment]
Alright that seems to do the trick aside from one issue, is there a way to get a mutable reference to the data with it?

**Comment by kangalioo** [comment]
There is not, because commands or events can be handled in parallel and mustn't modify the user data at the same time

Instead, use Mutex to wrap the specific data you need to modify

**Comment by Kirottu** [comment]
Alright that is reasonable enough, thanks for the help and the quick responses!
