### ISSUE TITLE
How to use this in a Rust project?

### ISSUE THREAD

**Issue by L1ghtingBolt** [kangalioo/poise#63]
I saw the crate is just a placeholder.

**Comment by kangalioo** [comment]
You used to depend on this crate using a git dependency `poise = { git = "https://github.com/kangalioo/poise" }`. However, I just published to crates.io, so you should now be able to use plain `poise = "0.1.0"` (:crossed_fingers:)

**Comment by devtomio** [comment]
🎉 [`poise 0.1.0`](https://crates.io/crates/poise) released
