### ISSUE TITLE
ThreadUpdate event?

### ISSUE THREAD

**Issue by Kirottu** [kangalioo/poise#65]
I used to use serenity's `thread_update` function in the event handler struct for this purpose. I tried using the `ChannelUpdate` event for this, but it seems to not be called for threads.

**Comment by kangalio** [comment]
Ah, the Event enum is missing events, thanks for catching it

Fixed in 6e56ac7d8eb2be31e7a04daef82780c907c126b1

**Comment by Kirottu** [comment]
Alright thanks again for the fast response, that would do it.
