### ISSUE TITLE
Provide some way to set default values for modals

### ISSUE THREAD

**Issue by elkowar** [kangalioo/poise#68]
According to the docs, discord allows you to set a default value for modal interaction fields.
It would be nice if these where supported dynamically in some way -- although I'm not sure how that'd look.
I think one way to structure that API would be to make the Modal derive-macro generate a second struct `<name>DefaultValues`,
which could contain fields for each field in the original modal that has been annotated with `#[has_default]`. Then you could provide an instance of that DefaultValues-struct when executing the modal interaction.

Alternatively, the macro could generate a builder struct that requires the defaults to be provided via functions, I guess

**Comment by kangalio** [comment]
Good idea

In addition to your two ideas, here's another one: a derived `Modal::create_with_defaults(defaults: Self)` method, where the defaults are taken from an instance of the type itself. Fields that don't need defaults would be assigned an empty string. (I tested; setting an empty string as default behaves like not setting a default at all)

```rust
#[derive(Default, poise::Modal)]
struct MyModal {
    field_1: String,
    field_2: String,
}

MyModal::create_with_defaults(MyModal {
    field_1: "Default value".into(),
    ..Default::default()
})
```

What do you think?

**Comment by elkowar** [comment]
That'd definitely be a cool option, too! Assuming that all the fields are Strings, that would work -- as soon as there are numbers etc in the struct, this doesn't work anymore, does it?

**Comment by kangalio** [comment]
Indeed

Currently, Discord forms only support text inputs, but once there are more types, my idea falls apart... That's also my main worry about the idea

**Comment by kangalio** [comment]
I just decided on the Default trait approach 4294264ef21289728a4c876e9317762cea000275
