### ISSUE TITLE
Allow specifying subcommands via the poise::command macro

### ISSUE THREAD

**Issue by elkowar** [kangalioo/poise#72]
Currently, specifying subcommands requires you to manually insert them into the Command struct, commonly done via 
```rs
Command {
  subcommands: vec![a(), b(), c()],
  ..foo()
}
```
which is quite cumbersome, especially if you're splitting up your commands into separate modules.

To improve this, I'd propose adding a `subcommands` attribute to the `poise::command` macro, which would allow specifying subcommands on the parent command like this:
```rs

#[poise::command(
  slash_command,
  subcommands(a, b, c)
]
pub fn foo(_: Context<'_>) -> Result<(), Error> {
  Ok(())
}
```

**Comment by kangalio** [comment]
b74066348369f62e37a4f27d3facb47cceb5ea0b
