### ISSUE TITLE
custom_data field for Commands

### ISSUE THREAD

**Issue by elkowar** [kangalioo/poise#76]
Currently, Commands are relatively limited in the amount of metadata you can provide to them.
There's the help-fields and the category, but both of those have specific usecases and are limited in what they can and should store.
It would be useful to be able to store arbitrary additional information together with the command declaration, thus allowing users of poise to implement their own system for keeping track of things such as specific permission requirements, additional help-data (i.e. usage examples, etc) and many other things.

After a short discussion of this in the serenity discord server, we came to the conclusion that it'd make sense to provide a `custom_data` field in the `poise::command` macro, which could store any user-provided struct together with the command, via a `Box<dyn Any>`.

I.e.:
```rs
#[poise::command(
  slash_command,
  custom_data=r#"CmdData { perm_level: PermissionLevel::Helpers, example: "/mute someguy 10m" }"#
)]
pub async fn mute(...) -> Result<()> {
...
}
```

**Comment by kangalio** [comment]
Implemented in 8f49befaa34e9c38b003ee64ea95d727a9bcaff9
