### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by Suya1671** [kangalioo/poise#79]
when https://github.com/serenity-rs/serenity/pull/1921 gets merged, how will this library handle localizations?

**Comment by kangalio** [comment]
My spontaneous plan was to add localized command names and descriptions and parameter names and descriptions as simple fields to Command and CommandParameter. You can set them as usual both via the attribute macros or programmatically (by modifying the struct fields). The former is useful to get started and for experimentation, the latter is useful to integrate real world translation frameworks

**Comment by jzeuzs** [comment]
https://github.com/serenity-rs/serenity/pull/1921 just got merged

**Comment by Suya1671** [comment]
How do you think the interface will look like in poise?

**Comment by kangalio** [comment]
First idea:

```rust
use crate::{Context, Error};
use poise::serenity_prelude as serenity;
use poise::ChoiceParameter;

#[derive(ChoiceParameter)]
enum WelcomeChoice {
    #[name = "Welcome to our cool server! Ask me if you need help"]
    #[name_localized(
        "de",
        "Willkommen auf unserem coolen Server! Frag mich, falls du Hilfe brauchst"
    )]
    A,
    #[name = "Welcome to the club, you're now a good person. Well, I hope."]
    #[name_localized(
        "de",
        "Willkommen im Club, du bist jetzt ein guter Mensch. Naja, hoffentlich."
    )]
    B,
    #[name = "I hope that you brought a controller to play together!"]
    #[name_localized("de", "Ich hoffe du hast einen Controller zum Spielen mitgebracht!")]
    C,
    #[name = "Hey, do you want a coffee?"]
    #[name_localized("de", "Hey, willst du einen Kaffee?")]
    D,
}

/// Welcome a user
#[poise::command(
    slash_command,
    name_localized("de", "begrüßen"),
    description_localized("de", "Einen Nutzer begrüßen")
)]
fn welcome(
    ctx: Context<'_>,
    #[name_localized("de", "nutzer")]
    #[description_localized("de", "Einen Nutzer begrüßen")]
    #[description = "The user to welcome"]
    user: serenity::User,
    #[name_localized("de", "nachricht")]
    #[description_localized("de", "Die versendete Nachricht")]
    #[description = "The message to send"]
    message: WelcomeChoice,
) -> Result<(), Error> {
    ctx.say(format!("<@{}> {}", user.id.0, message.name()))
        .await?;
    Ok(())
}
```

What do you think?

**Comment by Suya1671** [comment]
This has 1 major issue: intergration with external sources like crowdin

**Comment by kangalio** [comment]
> This has 1 major issue: intergration with external sources like crowdin

This use case is covered by the other approach I mentioned. See:
> You can set them as usual both via the attribute macros or programmatically (by modifying the struct fields). The former is useful to get started and for experimentation, the latter is useful to integrate real world translation frameworks

The snippet I posted is concerned with just the attribute macro part. Your use case is covered by the programmatical part

**Comment by Suya1671** [comment]
Send an example of the programming part

**Comment by kangalio** [comment]
Cobbled-together example of how it might look with GNU gettext (disclaimer: this is my first time interacting with gettext)

```rust
use gettextrs::*;

#[tokio::main]
async fn main() {
    let mut commands = vec![command1(), command2()];
    
    // This is the important part. Iterating over commands and inserting localizations
    for &locale in &["your", "locales", "here"] {
        setlocale(LocaleCategory::LcAll, locale);
        for command in &mut commands {
            command.name_localized.insert(locale, gettext(command.name));
            if let Some(description) = command.inline_help {
                command.description_localized.insert(locale, gettext(description));
            }
            for parameter in &mut command.parameters {
                parameter.name_localized.insert(locale, pgettext(command.name, parameter.name));
                if let Some(description) = parameter.description {
                    parameter.description_localized.insert(locale, pgettext(command.name, description));
                }
            }
        }
    }

    let framework = poise::Framework::build()
        .options(poise::FrameworkOptions { commands, ..Default::default() })
        // ...
}

```

**Comment by Suya1671** [comment]
What about arguments

**Comment by kangalio** [comment]
Updated example (will also remove the long quotations from your messages, I hope you don't mind)

**Comment by Suya1671** [comment]
> Updated example (will also remove the long quotations from your messages, I hope you don't mind)

~~What if 2 commands have the same argument name?~~ oh wait just name the keys command-arg

**Comment by kangalio** [comment]
They'll be localized completely fine, because they belong to separate commands

**Comment by Suya1671** [comment]
> They'll be localized completely fine, because they belong to separate commands

parameter.name_localized.insert(locale, gettextrs::gettext(parameter.name));
You are only using the parameter name, not the command name and the parameter name

On mobile for formatting is awful

**Comment by kangalio** [comment]
Ah you're right after all. Updated the example with using pgettext (translation with context).

In any case, the general idea of how to programmatically integrate localization should have come across by now

**Comment by Suya1671** [comment]
the api LGTM
