### ISSUE TITLE
Required feature flags for example are badly documented

### ISSUE THREAD

**Issue by s0lst1ce** [kangalioo/poise#8]
Running the example seems to fail:
```rs
error[E0433]: failed to resolve: could not find `CollectComponentInteraction` in `serenity`
   --> examples/framework_usage/commands.rs:113:37
    |
113 |     while let Some(mci) = serenity::CollectComponentInteraction::new(ctx.discord())
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `CollectComponentInteraction` in `serenity`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `poise` due to previous error```

**Comment by kangalioo** [comment]
The example requires the collector feature. If you run the example with `cargo run --example=framework_usage --features collector` it should work

**Comment by s0lst1ce** [comment]
Thanks. Should I make a PR to document that?

**Comment by kangalioo** [comment]
Well it is documented in the README though it seems I chose an unfortunate place for it :smile:

> You can run the framework_usage example with cargo run --example=framework_usage --features collector

Feel free to make a PR to make the information more visible

**Comment by kangalioo** [comment]
Thanks for the PR!
