### ISSUE TITLE
Event handler mutable

### ISSUE THREAD

**Issue by vulcandragi** [kangalioo/poise#91]
Hello good night, could you help me? I'm trying to use the event handler but for some functions for example add role I need the new member to be mutable, but from what I noticed the event cannot be mutable, would you have any solution?

temporary solution:
```rust
Event::GuildMemberAddition { new_member } => {
    let roles = new_member.guild_id.roles(ctx).await.map_app_err()?;

    let role = roles.iter().find(|x| x.1.name == "alguma coisa");
    let role = role.unwrap();

    let mut member = new_member.clone();

    member.add_role(ctx, role.0).await.map_app_err()?;
}
```

**Comment by kangalio** [comment]
Instead of the model methods (Member::add_role), you can use the underlying HTTP method directly: Http::add_member_role.

`ctx.http.add_member_role(member.guild_id.0, member.user.id.0, role.0.0, None)`

**Comment by vulcandragi** [comment]
oh yes thank you very much for the help
