### ISSUE TITLE
Duplicate entries of slash commands if register_application_commands() is ran for both local and global.

### ISSUE THREAD

**Issue by BuyMyMojo** [kangalioo/poise#98]
when executing register_application_commands() in a server it will show two options for every slash command added if you do both local and global. is there a way to remove the local ones from this server?

![](https://s3.buymymojo.net/ShareX/2022/07/Discord_YTYNI5eSJK.png)

**Comment by kangalio** [comment]
Use register_application_commands_button(), which also supports removing commands

![image](https://user-images.githubusercontent.com/21220820/181466683-6ae0968a-2980-4a1c-a26f-c96c97330da0.png)

To remove local commands, click Delete in guild
